var Member=require("../models/member")
var express=require("express");
var router=express.Router();
var multer=require("multer");
var storage=multer.diskStorage({
    destination:function(req,file,cb){
      cb(null,'uploads/');
    },
    filename:function(req,file,cb){
      cb(null,new Date().toISOString()+file.originalname);
    }
  });
  var upload=multer({storage:storage});
router.get("/newmember",function(req,res){
    res.render("newmember");
  })
  router.post("/newmember",upload.single('member[file]'),function(req,res){
    Member.create({
      file:req.file.path,
      name:req.body.member.name,
      designation:req.body.member.designation,
      linkedIn:req.body.member.linkedIn
    })
    res.redirect("/adminhome")
  })
  router.get("/editmember",function(req,res){
    Member.find({},function(err,members){
      if(err)
      console.log("err")
      else
      res.render("editmember",{members:members})
    })
  })
  router.get("/:id/editmember",function(req,res){
    Member.findById(req.params.id,function(err,foundMember){
      console.log(req.params.id);
      if(err){
          res.redirect("/");
      }
      else{
          res.render("showmember",{member:foundMember});
      }
  })
  })
  router.delete("/:id/editmember",function(req,res){
    Member.findByIdAndRemove(req.params.id,function(err){
      console.log(req.params.id);
        if(err){
            res.redirect("/editmember")
        }
        else{
            res.redirect("/editmember")
        }
    })
  })
  router.get("/:id/changephotomember",function(req,res){
    Member.findById(req.params.id,function(err,foundMember){
        if(err){
            console.log("Error");
        }
        else{
            res.render("changephotomember",{member:foundMember})
        }
    }) 
  })
  router.post("/:id/changephotomember",upload.single("member[file]",{overwrite:true}),function(req,res){
    console.log(req.file.path)
         Member.findByIdAndUpdate(req.params.id,{file:req.file.path},function(err){
            if(err){
                res.redirect("/adminhome");
            }
            else{
                res.redirect("/editmember");
            }
        })
    })
    router.get("/:id/editmemberform",function(req,res){
      Member.findById(req.params.id,function(err,foundMember){
        if(err){
          console.log("err")
        }
        else{
          res.render("editmemberform",{member:foundMember})
        }
      })
    })
    router.post("/:id/editmemberform",function(req,res){
      Member.findByIdAndUpdate(req.params.id,req.body.member,function(err){
           if(err){
               res.redirect("/adminhome");
           }
           else{
               res.redirect("/editmember");
           }
       })
     })
     module.exports=router;