var News=require("../models/news");
var express=require("express");
var router=express.Router();
var multer=require("multer");
var storage=multer.diskStorage({
    destination:function(req,file,cb){
      cb(null,'uploads/');
    },
    filename:function(req,file,cb){
      cb(null,new Date().toISOString()+file.originalname);
    }
  });
  var upload=multer({storage:storage});


router.get("/newnews",function(req,res){
    res.render("newnews");
  })
  router.post("/newnews",upload.single('news[file]'),function(req,res){
    News.create({
      title:req.body.news.title,
      file:req.file.path,
      desc:req.body.news.desc,
      time:Date.now()
    })
    res.redirect("/adminhome")
  })
  router.get("/editnews",function(req,res){
    News.find({},function(err,newss){
      if(err)
      console.log("err")
      else
      res.render("editnews",{newss:newss})
    })
  })
  router.get("/:id/editnews",function(req,res){
    News.findById(req.params.id,function(err,foundNews){
      console.log(req.params.id);
      if(err){
          res.redirect("/");
      }
      else{
          res.render("shownews",{news:foundNews});
      }
  })
  })
  router.delete("/:id/editnews",function(req,res){
    News.findByIdAndRemove(req.params.id,function(err){
      console.log(req.params.id);
        if(err){
            res.redirect("/editnews")
        }
        else{
            res.redirect("/editnews")
        }
    })
  })
  router.get("/:id/changephotonews",function(req,res){
    News.findById(req.params.id,function(err,foundNews){
        if(err){
            console.log("Error");
        }
        else{
            res.render("changephotonews",{news:foundNews})
        }
    }) 
  })
  router.post("/:id/changephotonews",upload.single("news[file]",{overwrite:true}),function(req,res){
    console.log(req.file.path)
         News.findByIdAndUpdate(req.params.id,{file:req.file.path},function(err){
            if(err){
                res.redirect("/adminhome");
            }
            else{
                res.redirect("/editnews");
            }
        })
    })
    router.get("/:id/editnewsform",function(req,res){
      News.findById(req.params.id,function(err,foundNews){
        if(err){
          console.log("err")
        }
        else{
          res.render("editnewsform",{news:foundNews})
        }
      })
    })
    router.post("/:id/editnewsform",function(req,res){
      News.findByIdAndUpdate(req.params.id,req.body.news,function(err){
           if(err){
               res.redirect("/adminhome");
           }
           else{
               res.redirect("/editnews");
           }
       })
     })
     module.exports=router;